[calendar.defaults]
start_date = "2026-01-12"
end_date = "2026-04-28"
event_color = 1


[calendar.exclusions]
excluded_dates = [
    "2026-01-26",              # Republic Day
    "2026-02-20 - 2026-02-21", # Breeze
    "2026-03-02 - 2026-03-10", # Midsems
    "2026-03-21",              # Eid
    "2026-04-09",              # SNU day
    "2026-04-14",              # Ambedkar Jayanti
]

[locale]
timezone = "Asia/Kolkata"

[execution]
run_headless_browser = false
